# InterviewPrep: NLP [Fall 2023]
## Day 2

In [ ]:
##Importing Packages
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

**TF-IDF**

In [ ]:
Document1 = "It is going to rain today."
Document2 = "Today I am not going Outside."
Document3 = "I am going to watch the season premiere."

In [ ]:
cou = [Document1, Document2, Document3]

In [ ]:
cou

['It is going to rain today.',
 'Today I am not going Outside.',
 'I am going to watch the season premiere.']

In [ ]:
tf_idf = TfidfVectorizer()

In [ ]:
x = tf_idf.fit_transform(cou)

In [ ]:
vocab = tf_idf.vocabulary_

In [ ]:
tf_idf.get_feature_names_out()

array(['am', 'going', 'is', 'it', 'not', 'outside', 'premiere', 'rain',
       'season', 'the', 'to', 'today', 'watch'], dtype=object)

In [ ]:
x.toarray()[0]

array([0.        , 0.27824521, 0.4711101 , 0.4711101 , 0.        ,
       0.        , 0.        , 0.4711101 , 0.        , 0.        ,
       0.35829137, 0.35829137, 0.        ])

In [ ]:
cou[0]

'It is going to rain today.'

In [ ]:
tf_idf.idf_[6]

1.6931471805599454

In [ ]:
for feature in tf_idf.get_feature_names_out():
  indx = vocab[feature]
  print(f"Feature: {feature} - IDF Value: {tf_idf.idf_[indx]}")

Feature: am - IDF Value: 1.2876820724517808
Feature: going - IDF Value: 1.0
Feature: is - IDF Value: 1.6931471805599454
Feature: it - IDF Value: 1.6931471805599454
Feature: not - IDF Value: 1.6931471805599454
Feature: outside - IDF Value: 1.6931471805599454
Feature: premiere - IDF Value: 1.6931471805599454
Feature: rain - IDF Value: 1.6931471805599454
Feature: season - IDF Value: 1.6931471805599454
Feature: the - IDF Value: 1.6931471805599454
Feature: to - IDF Value: 1.2876820724517808
Feature: today - IDF Value: 1.2876820724517808
Feature: watch - IDF Value: 1.6931471805599454


**BoW**

In [ ]:
Document1 = "the cat in the hat"
Document2 = "the dog in the house"
Document3 = "the bird in the sky"

In [ ]:
cou = [Document1, Document2, Document3]

In [ ]:
cou

['the cat in the hat', 'the dog in the house', 'the bird in the sky']

In [ ]:
bow = CountVectorizer()

In [ ]:
dir(bow)

['__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_feature_names',
 '_check_n_features',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_get_param_names',
 '_get_tags',
 '_limit_features',
 '_more_tags',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr_mimebundle_',
 '_sort_features',
 '_validate_data',
 '_validate_ngram_range',
 '_validate_params',
 '_validate_vocabulary',
 '_warn_for_unused_params',
 '_white_spaces',
 '_word_ngrams',
 'analyzer',
 'binary',
 'build_analyzer',
 'build_preprocessor',
 'build_tokenizer',
 'de

In [ ]:
x = bow.fit_transform(cou)

In [ ]:
x.toarray()[1]

array([0, 0, 1, 0, 1, 1, 0, 2])

In [ ]:
bow.get_feature_names_out()

array(['bird', 'cat', 'dog', 'hat', 'house', 'in', 'sky', 'the'],
      dtype=object)

In [ ]:
cou[1]

'the dog in the house'

In [ ]:
bow.vocabulary_

{'the': 7,
 'cat': 1,
 'in': 5,
 'hat': 3,
 'dog': 2,
 'house': 4,
 'bird': 0,
 'sky': 6}

**N-Gram**

In [ ]:
text = ["The dog in the house"]

In [ ]:
ngram = CountVectorizer(ngram_range = (2,3))

In [ ]:
x = ngram.fit_transform(text)

In [ ]:
ngram.get_feature_names_out()

array(['dog in', 'dog in the', 'in the', 'in the house', 'the dog',
       'the dog in', 'the house'], dtype=object)

In [ ]:
x.toarray()

array([[1, 1, 1, 1, 1, 1, 1]])